CREATE TABLE url_mapping (
    id BIGSERIAL PRIMARY KEY,
    original_url VARCHAR(255) NOT NULL,
    shortened_url VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);